import { StyleSheet } from 'react-native';
import { COLORS } from './GlobalStyles';

export const ProfileStyles = StyleSheet.create({
  // ========== Layout ==========
  screen: { flex: 1, backgroundColor: COLORS.background },
  main: { flex: 1, backgroundColor: COLORS.background },
  loadingScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.background,
  },
  scrollContent: { paddingBottom: 40 },
  flex1: { flex: 1 },

  // ========== Top Bar (đồng bộ Dashboard) ==========
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 14,
    gap: 10,
  },
  heading: { flex: 1, minWidth: 0 },
  greeting: {
    fontSize: 10,
    letterSpacing: 1.2,
    fontWeight: '800',
    color: COLORS.textSecondary,
  },
  topTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
    marginTop: 2,
    letterSpacing: -0.3,
  },
// Trong ProfileStyles.ts - thêm vào phần "Top Bar"
backButton: {
  width: 42,
  height: 42,
  borderRadius: 14,
  backgroundColor: COLORS.surface,
  alignItems: 'center',
  justifyContent: 'center',
  shadowColor: COLORS.shadow,
  shadowOpacity: 0.07,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
},
backButtonText: {
  fontSize: 22,
  color: COLORS.textPrimary,
  fontWeight: '600',
  marginTop: -3,
},
  // ========== Logout Button (rõ ràng, có chữ) ==========
  logoutBtn: {
    height: 42,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: COLORS.dangerSoft,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  logoutBtnPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.97 }],
  },
  logoutIcon: {
    fontSize: 15,
    color: COLORS.danger,
    fontWeight: '900',
    lineHeight: 17,
  },
  logoutText: {
    color: COLORS.danger,
    fontSize: 12.5,
    fontWeight: '800',
    letterSpacing: 0.2,
  },

  pressed: { opacity: 0.85 },

  // ========== Profile Hero (avatar + tên + email) ==========
  profileHero: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 18,
    borderRadius: 22,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  avatarText: { color: COLORS.white, fontSize: 24, fontWeight: '900' },
  profileHeroBody: { flex: 1, minWidth: 0 },
  profileName: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  profileEmail: {
    fontSize: 12.5,
    color: COLORS.textSecondary,
    marginTop: 3,
  },
  rolePill: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.accentSoft,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 8,
    marginTop: 6,
  },
  rolePillAdmin: { backgroundColor: COLORS.primarySoft },
  rolePillText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#B45309',
    letterSpacing: 0.3,
  },
  rolePillTextAdmin: { color: COLORS.primaryDark },

  // ========== Wallet Hero (chỉ buyer) ==========
  walletHero: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 20,
    borderRadius: 22,
    backgroundColor: COLORS.primary,
    overflow: 'hidden',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  walletHeroBlobA: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.10)',
    top: -50,
    right: -30,
  },
  walletHeroBlobB: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(245,158,11,0.30)',
    bottom: -30,
    right: 30,
  },
  walletHeroLabel: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: 'rgba(255,255,255,0.75)',
  },
  walletHeroAmount: {
    fontSize: 28,
    fontWeight: '900',
    color: COLORS.white,
    marginTop: 6,
    letterSpacing: -0.6,
  },
  walletHeroBtn: {
    alignSelf: 'flex-start',
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.20)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  walletHeroBtnText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.3,
  },

  // ========== Admin Quick Actions ==========
  adminSectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: COLORS.textSecondary,
    marginHorizontal: 20,
    marginBottom: 10,
    marginTop: 4,
  },
  adminActionCard: {
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  adminActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: COLORS.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminActionIconText: { fontSize: 18 },
  adminActionBody: { flex: 1, minWidth: 0 },
  adminActionLabel: {
    fontSize: 13.5,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  adminActionHint: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  adminActionChevron: {
    fontSize: 18,
    color: '#C9CCDD',
    fontWeight: '700',
  },

  // ========== Tab Bar (pill style) ==========
  tabBar: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 4,
    borderRadius: 16,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  tabButtonText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: COLORS.textSecondary,
  },
  tabButtonTextActive: { color: COLORS.white },

  // ========== Section Title ==========
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: COLORS.textSecondary,
    marginHorizontal: 20,
    marginBottom: 10,
    marginTop: 4,
  },

  // ========== Card chung ==========
  card: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 18,
    borderRadius: 20,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },

  // ========== Info Row (email hiển thị) ==========
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  infoLabel: {
    fontSize: 12.5,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  infoValue: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textPrimary,
    maxWidth: '65%',
    textAlign: 'right',
  },
  infoHint: {
    fontSize: 11.5,
    color: COLORS.textMuted,
    marginTop: 4,
    fontStyle: 'italic',
  },

  // ========== Form ==========
  inputLabel: {
    fontSize: 12.5,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: 8,
    marginLeft: 3,
  },
  input: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: COLORS.textPrimary,
    backgroundColor: COLORS.inputBg,
    marginBottom: 14,
  },
  inputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  primaryBtn: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginTop: 4,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  primaryBtnText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  outlineBtn: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  outlineBtnText: {
    color: COLORS.primary,
    fontSize: 13.5,
    fontWeight: '800',
  },

  // ========== Order Item ==========
  orderItem: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    borderRadius: 18,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  orderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  orderId: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  orderStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  orderStatusText: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  orderProductLine: {
    fontSize: 13.5,
    color: COLORS.textPrimary,
    fontWeight: '600',
    marginTop: 4,
    lineHeight: 19,
  },
  orderDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginTop: 10,
    marginBottom: 8,
  },
  orderTotal: {
    fontSize: 16,
    fontWeight: '900',
    color: COLORS.primaryDark,
    letterSpacing: -0.2,
  },

  // ========== Empty Orders ==========
  emptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
    paddingHorizontal: 32,
  },
  emptyIcon: { fontSize: 56, marginBottom: 14 },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.textPrimary,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginTop: 8,
  },
  emptyButton: {
    marginTop: 20,
    paddingHorizontal: 22,
    height: 46,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  emptyButtonText: {
    color: COLORS.white,
    fontWeight: '800',
    fontSize: 14,
  },
});